### ISSUE TITLE
strings.mdの翻訳

### ISSUE THREAD

**Issue by m0ch1m0ch1** [fms-lab/julia-doc-ja#13]

**Comment by jabelic** [comment]
May I work on it?

**Comment by m0ch1m0ch1** [comment]
I’m sorry for the delayed response.

> May I work on it? @m0ch1m0ch1

Of course! I'll be happy with that.

**Comment by m0ch1m0ch1** [comment]
I've given you Write Permission to this repository.
If you have any problems with permissions, please contact me.
